DROP TABLE IF EXISTS Shopping_Cart_Employee;
DROP TABLE IF EXISTS Pizza_Order;
DROP TABLE IF EXISTS Shopping_Cart;
DROP TABLE IF EXISTS Order_status;
DROP TABLE IF EXISTS Promo_Codes;
DROP TABLE IF EXISTS Size;
DROP TABLE IF EXISTS PizzaToppings;
DROP TABLE IF EXISTS Toppings;
DROP TABLE IF EXISTS Pizza;
DROP TABLE IF EXISTS Pizza_Type;
DROP TABLE IF EXISTS Employee;
DROP TABLE IF EXISTS Customer;
DROP TABLE IF EXISTS Job_Position;
DROP TABLE IF EXISTS Address;


CREATE TABLE Address
(
    Address_ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY	NOT NULL,
	City VARCHAR(100)	NOT NULL,
	Street VARCHAR(100)	NOT NULL,
	House_Number INT	NOT NULL,
	Apartment_Number	INT,
	ZIP_Code	VARCHAR(7)	NOT NULL
);


CREATE TABLE Job_Position
(
	Job_Position_ID	INT AUTO_INCREMENT	NOT NULL PRIMARY KEY,
	Position_Name	VARCHAR(100)	NOT NULL
);


CREATE TABLE Customer
(
	Customer_ID	INT	AUTO_INCREMENT	NOT NULL	PRIMARY KEY,
	Customer_Name	VARCHAR(50)	NOT NULL,
	Customer_Surname	VARCHAR(50)	NOT NULL,
	Customer_Phone_Number VARCHAR(11)	NOT NULL,
	Customer_Email	VARCHAR(50)	NOT NULL,
    
    Customer_Username	VARCHAR(50)	NOT NULL UNIQUE,
    Customer_Password	VARCHAR(50)	NOT NULL,

	Address_ID	INT,
    CONSTRAINT  FOREIGN KEY (Address_ID) REFERENCES Address(Address_ID) ON DELETE SET NULL
);



CREATE TABLE Employee
(
	Employee_ID	INT	AUTO_INCREMENT	NOT NULL	PRIMARY KEY,
	Employee_Name	VARCHAR(50)	NOT NULL,
	Employee_Surname	VARCHAR(50)	NOT NULL,
	Employee_Date_Of_Birth	DATE	NOT NULL,
	Employee_Phone_Number VARCHAR(10) NOT NULL,
	Employee_Email	VARCHAR(50)	NOT NULL,
	Employee_PESEL	VARCHAR(11)	NOT NULL UNIQUE,
	Employee_Salary	DECIMAL	NOT NULL,
    
	Employee_Username	VARCHAR(50)	NOT NULL UNIQUE,
    Employee_Password	VARCHAR(50)	NOT NULL,

	Address_ID	INT,
    CONSTRAINT  FOREIGN KEY (Address_ID) REFERENCES Address(Address_ID) ON DELETE SET NULL,
    
	Job_Position_ID INT	NOT NULL,
    CONSTRAINT  FOREIGN KEY (Job_Position_ID) REFERENCES Job_Position(Job_Position_ID) ON DELETE CASCADE
);


CREATE TABLE Pizza_Type
(
	Pizza_Type_ID	INT	AUTO_INCREMENT	NOT NULL	PRIMARY KEY,
	Pizza_Type	VARCHAR(100)	NOT NULL
);

CREATE TABLE Pizza
(
	Pizza_ID	INT	AUTO_INCREMENT	NOT NULL	PRIMARY KEY,
	Pizza_Name	VARCHAR(100)	NOT NULL,
    
    Pizza_Type_ID	INT NOT NULL,
    CONSTRAINT  FOREIGN KEY (Pizza_Type_ID) REFERENCES Pizza_Type(Pizza_Type_ID) ON DELETE CASCADE
);


CREATE TABLE Toppings
(
	Toppings_ID	INT AUTO_INCREMENT	NOT NULL	PRIMARY KEY,
	Topping_Name	VARCHAR(100)	NOT NULL
);

CREATE TABLE PizzaToppings
(
	Pizza_ID	INT	NOT NULL,
    CONSTRAINT  FOREIGN KEY (Pizza_ID) REFERENCES Pizza(Pizza_ID) ON DELETE CASCADE,
    
	Topping_ID	INT	NOT NULL,
    CONSTRAINT  FOREIGN KEY (Topping_ID) REFERENCES Toppings(Toppings_ID) ON DELETE CASCADE,

	PRIMARY KEY(Pizza_ID, Topping_ID)
);


CREATE TABLE Size
(
	Size_ID	INT AUTO_INCREMENT	NOT NULL	PRIMARY KEY,
	Size	VARCHAR(10)	NOT NULL,
	Price	DECIMAL	NOT NULL
);

CREATE TABLE Promo_Codes
(
	Promo_Code_ID	INT AUTO_INCREMENT	NOT NULL	PRIMARY KEY,
    Promo_Code	VARCHAR(50)	NOT NULL,
    Discount INT NOT NULL
);

CREATE TABLE Order_status
(
	Order_status_ID	INT AUTO_INCREMENT	NOT NULL	PRIMARY KEY,
    Order_status	VARCHAR(50)	NOT NULL
);

CREATE TABLE Shopping_Cart
(
	Shopping_Cart_ID	INT AUTO_INCREMENT	NOT NULL	PRIMARY KEY,
    
    Customer_ID	INT	NOT NULL,
    CONSTRAINT  FOREIGN KEY (Customer_ID) REFERENCES Customer(Customer_ID) ON DELETE CASCADE,
    
    Address_ID INT,
    CONSTRAINT  FOREIGN KEY (Address_ID) REFERENCES Address(Address_ID)ON DELETE SET NULL,
    
    Promo_Code_ID	INT,
    CONSTRAINT  FOREIGN KEY (Promo_Code_ID) REFERENCES Promo_Codes(Promo_Code_ID) ON DELETE SET NULL,
    
    Order_status_ID	INT	NOT NULL,
    CONSTRAINT  FOREIGN KEY (Order_status_ID) REFERENCES Order_status(Order_status_ID)ON DELETE CASCADE
);

CREATE TABLE Pizza_Order
(
	Order_ID	INT	AUTO_INCREMENT	NOT NULL	PRIMARY KEY,
	
	Pizza_ID	INT	NOT NULL,
    CONSTRAINT  FOREIGN KEY (Pizza_ID) REFERENCES Pizza(Pizza_ID)	ON DELETE CASCADE,
    
	Size_ID	INT	NOT NULL,
    CONSTRAINT  FOREIGN KEY (Size_ID) REFERENCES Size(Size_ID)	ON DELETE CASCADE,
    
    Shopping_Cart_ID	INT	NOT NULL,
    CONSTRAINT  FOREIGN KEY (Shopping_Cart_ID) REFERENCES Shopping_Cart(Shopping_Cart_ID)	ON DELETE CASCADE
);

CREATE TABLE Shopping_Cart_Employee
(
	Shopping_Cart_ID	INT	NOT NULL,
    CONSTRAINT  FOREIGN KEY (Shopping_Cart_ID) REFERENCES Shopping_Cart(Shopping_Cart_ID)	ON DELETE CASCADE,
    
	Employee_ID	INT NOT NULL,
    CONSTRAINT  FOREIGN KEY (Employee_ID) REFERENCES Employee(Employee_ID)	ON DELETE CASCADE,

	PRIMARY KEY(Shopping_Cart_ID, Employee_ID)
);
 